services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: legal-rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: legal_rag
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: