CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.legal_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id TEXT NOT NULL UNIQUE,
    article_number INTEGER NOT NULL,
    text_ar TEXT,
    text_ar_normalized TEXT,
    text_en TEXT,
    book TEXT,
    chapter TEXT,
    section TEXT,
    topic TEXT,
    is_repealed BOOLEAN DEFAULT FALSE,
    source_page INTEGER,
    citation TEXT,
    embedding VECTOR(384),
    search_vector TSVECTOR
);
